@startuml
title Архитектура системы Smetaniny\ReactAdminRouting

!define RECTANGLE class
!define CIRCLE interface

package "Smetaniny\ReactAdminRouting" {
    RECTANGLE Controllers {
        RECTANGLE LoginAdminController
        RECTANGLE PagesAdminController
        RECTANGLE UsersAdminController
        RECTANGLE UsersController
        RECTANGLE RolesAdminController
        RECTANGLE PermissionsAdminController
        RECTANGLE GroupPermissionAdminController
    }

    RECTANGLE Models {
        RECTANGLE UsersAdminModel
        RECTANGLE RolesModel
        RECTANGLE PermissionsModel
        RECTANGLE ProductsModel
        RECTANGLE PagesModel
        RECTANGLE GroupPermissionModel
    }

    RECTANGLE Middleware {
        RECTANGLE AdminMiddleware
        RECTANGLE RoleAdminMiddleware
    }

    RECTANGLE Services {
        RECTANGLE AdminRouteHandlerServices
        RECTANGLE ResourceShowService
        RECTANGLE ResourceStrategyFirstService
        RECTANGLE ResourceStrategyGetService
    }

    RECTANGLE Factories {
        RECTANGLE RouteHandlerFactory
        RECTANGLE AdminRouteHandlerFactory
    }

    RECTANGLE Policies {
        RECTANGLE PagesPolicy
        RECTANGLE UsersPolicy
        RECTANGLE RolesPolicy
        RECTANGLE PermissionsPolicy
        RECTANGLE GroupPermissionPolicy
    }

    RECTANGLE Exceptions {
        RECTANGLE RouteHandlerAdminException
        RECTANGLE UnauthorizedAdminException
        RECTANGLE ResourceNotFoundException
    }

    RECTANGLE Enums {
        RECTANGLE UserAdminRole
    }

    RECTANGLE Facades {
        RECTANGLE RouteHandlerFactoryFacade
    }
}

Controllers --> Services : Используют
Services --> Models : Обрабатывают данные
Middleware --> Controllers : Проверяют доступ
Factories --> Services : Создают объекты
Facades --> Factories : Облегчают доступ
Policies --> Models : Контролируют доступ
Exceptions --> Controllers : Обрабатывают ошибки
Controllers --> Policies : Используют
Models --> Enums : Используют
Services --> Exceptions : Обрабатывают ошибки
@enduml
